const PREFIX = "SERVER_";
module.exports = {
    CREATE_GAME_SUCCESS: `${PREFIX}CREATE_GAME_SUCCESS`,
    JOIN_GAME_SUCCESS: `${PREFIX}JOIN_GAME_SUCCESS`,
    ENOUGH_PLAYERS: `${PREFIX}ENOUGH_PLAYERS`,
    OPPONENT_READY: `${PREFIX}OPPONENT_READY`,
    START_GAME: `${PREFIX}START_GAME`,
    GAME_ERROR: `${PREFIX}GAME_ERROR`,
};